version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo Entering install phase...
      - echo Nothing to do now
  build:
    commands:
      - echo Build started on `date`
      - gradle assemble
      - gradle build
artifacts:
  type: zip
  files:
    - 'build/libs/*.jar'
cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '.gradle/**/*'
    - '/root/.gradle/wrapper/**/*'
